### ISSUE TITLE
Homepage bug [BUG]

### ISSUE THREAD

**Issue by Blackgaurd** [jdabtieu/CTFOJ#100]
Please use this template only for reporting bugs. Bug reports not using this template may be denied.

## Describe the bug
The "see more" button on the homepage under certain posts does not actually allow the user to expand text.

## Expected Behavior
Extend the post length or add a scrollable snippet.

## Current Behavior
After clicking "see more" most of the text is inaccessible.

## Possible Solution
Add a scroll thing.

## Steps to Reproduce
Provide a link to a video showing off the bug or steps to trigger the bug.
1. Go to homepage
2. Under the "MGCI - WLMAC CTF Competition" announcement click "see more"
3.
4.

## Context (Environment)
Literally just reloaded the page.

## Additional Information
![Capture](https://user-images.githubusercontent.com/61335502/119042102-69198080-b985-11eb-9871-f4df96d935b0.JPG)
![Capture(1)](https://user-images.githubusercontent.com/61335502/119042179-7d5d7d80-b985-11eb-91b7-e1a854d765fd.JPG)

**Comment by jdabtieu** [comment]
The current site runs on version v2.4.1-pre1 (not the latest version), and the bug has been fixed since then, in commit f4af1bd.

The solution was to change
```
e.parentElement.parentElement.style.maxHeight = "";
```
to
```
e.parentElement.parentElement.style.maxHeight = "none";
```

Thanks for reporting the bug, but since it was already fixed this is a duplicate.
