### ISSUE TITLE
Better docs

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#108]
While I was looking at a certain problem setters quiz and scrolling through that site's docs, I realized two things:
1. The docs are awful at describing the functionality of the site
2. Our docs are awful at describing the functionality of CTFOJ

There are some massive improvements we need to make to our docs (and related things). Here's a list of everything I can think of right now:
- [x] INSTALL.sh should use `python application.py` instead of `export FLASK_APP=application.py` and `flask run`
- [x] Install script should recommend the use of a venv, in both manual installation and the INSTALL.sh
- [ ] Documentation for how the database and filesystem store info does not exist
- [ ] Most site functions don't have documentation
    - [ ] Non-intuitive site functions don't have documentation (e.g. what does min & max point value mean in the context of dynamically scored problems?)
- [ ] Update API documentation for v4
 
The addition & improvement of our docs will make it easier for users to navigate the site functionality (especially admin functionality) and for developers looking to contribute but cannot find anything to ease any confusion about the code/database

**Comment by slightlyskepticalpotat** [comment]
todo for myself: wiki page describing how to customise the look and functionality of an install.
