### ISSUE TITLE
[FEATURE] Validate Settings

### ISSUE THREAD

**Issue by slightlyskepticalpotat** [jdabtieu/CTFOJ#117]
## Is your feature request related to a problem? Please describe.
Settings often aren't validated until something goes wrong, leading to unexpected behaviour.

## Describe the solution you'd like
Ideally we should validate them at startup and warn/terminate on any errors. Also, we should let users configure their homepage file location.

## Additional context
Settings we should validate are the smtp/hcaptcha/homepage existence ones, if they're enabled.

**Comment by jdabtieu** [comment]
BTW, for the homepage file, I think I'm going to change its location to the metadata folder instead, as it makes more sense there. Also, it might be nice to provide a default homepage file that people can edit instead of having people start from scratch.
