### ISSUE TITLE
[BUG] Client-side datetime broken on certain platforms

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#15]
Please use this template only for reporting bugs. Bug reports not using this template may be denied.

## Describe the bug
Converting UTC time returned by the server to local time does not work in some environments

## Expected Behavior
A time such as `2020-11-11 13:00:00` should be converted into (assume local time = UTC-4) `Nov 11, 2020 09:00:00`

## Current Behavior
Times get converted into `Date undefined, undefined undefined`

## Possible Solution
???
Will need to do more testing to find a cause. It has to do with the Date toString() function (see below)

## Steps to Reproduce
1. View any Date object (users page, announcement, or contest start/end date)

## Context (Environment)
Arch Linux, Firefox

Works on Windows 10, Edge

## Additional Information
Relevant code:
```
    document.querySelectorAll(".dt").forEach(function (e) {
        var parsed = new Date(e.innerHTML + " UTC").toString().split(" ");
        e.innerHTML = "Posted " + parsed[1] + " " + parsed[2] + ", " + parsed[3] + " " + parsed[4];
    });
```

**Comment by ComputerGenius152** [comment]
works on chromium and ubuntu, I don't think this is a linux issue
