### ISSUE TITLE
[FEATURE] Delete announcement/problem/contest

### ISSUE THREAD

**Issue by ComputerGenius152** [jdabtieu/CTFOJ#16]
## Is your feature request related to a problem? Please describe.
N/A

## Describe the solution you'd like
Button to delete announcement/problem/contest, in the edit interface

## Describe alternatives you've considered
Manually using SQL is bad

## Additional context
N/A

**Comment by jdabtieu** [comment]
This should be easy enough to implement

For announcements it's one DELETE command
For problems it's one ALTER and one DELETE
For contests it's two DROP and one DELETE

**Comment by jdabtieu** [comment]
- [x] Delete announcements
- [ ] Delete problems
- [ ] Delete contests

**Comment by jdabtieu** [comment]
small problem: SQLite doesn't support ALTER TABLE DROP COLUMN

the code to delete problems might be a bit complicated

**Comment by jdabtieu** [comment]
Test code for deleting problem from problems_master
it's very sketchy, and has a lot of hard coded values that may pose a problem in the future
will try to produce cleaner code sometime later
```python
import cs50
import re

db = cs50.SQL("sqlite:///test.db")

bad = "'helloworld2'"  # test.db contains a problem called helloworld2

db.execute("BEGIN")
schema = db.execute("SELECT sql FROM sqlite_master WHERE tbl_name='problems_master'")[0]["sql"]
db.execute("CREATE TABLE 'pm_tmp' " + schema[schema.index('('):schema.index(bad)] +
           schema[schema.index(bad) + schema[schema.index(bad):].index(',') + 2:])
data = db.execute("SELECT * FROM problems_master")
for row in data:
    row.pop(bad[1:-1], None)
    row = str(row)[1:-1]
    row = re.sub(r"'[A-Za-z0-9_\-]{1,}': ", "", row)
    db.execute("INSERT INTO pm_tmp " + 'VALUES(' + row + ')')
db.execute("DROP TABLE problems_master")
db.execute("ALTER TABLE pm_tmp RENAME TO problems_master")
db.execute("COMMIT")
```

**Comment by jdabtieu** [comment]
Suspended, pending #28.
Changing the structure of problems_master to the proposed format would change the SQL commands to delete problems significantly
