### ISSUE TITLE
[BUG] edit problem crashing

### ISSUE THREAD

**Issue by ComputerGenius152** [jdabtieu/CTFOJ#18]
Please use this template only for reporting bugs. Bug reports not using this template may be denied.

## Describe the bug
any attempt to edit a created problem leads to an internal server error

## Expected Behavior
i expected to be able to edit the problem

## Current Behavior
it crashes and leads to an internal server error

## Possible Solution
check server logs

## Steps to Reproduce
1. obtain admin perms
2. go to problem
3. edit problem
4. crash

## Context (Environment)
What were you doing right before this bug happened that might have triggered it?
chromium 86, ubuntu 20.04 lts. it crashed at 19:54 

## Additional Information
Please put anything not already mentioned here, including screenshots.
![image](https://user-images.githubusercontent.com/31290848/99014543-dce35800-2520-11eb-8d82-1b028bb09872.png)

**Comment by jdabtieu** [comment]
![image](https://user-images.githubusercontent.com/62577178/99014687-2af85b80-2521-11eb-8b15-237ed4321fb7.png)

This might just be a case of me forgetting to update the database

**Comment by jdabtieu** [comment]
Database was missing hints column, not a bug.
