### ISSUE TITLE
[FEATURE] Resend confirmation email

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#20]
## Is your feature request related to a problem? Please describe.
Related to #19 
After sending the confirmation email, if the user doesn't click it in time they are permanently locked out of their account unless an admin manually updates it through SQLite

## Describe the solution you'd like
Allow users to resend confirmation email after certain time period

## Describe alternatives you've considered
None

## Additional context
None

**Comment by ComputerGenius152** [comment]
@jdabtieu need your thoughts on this, how should I implement this

- include a link in the email to request a resend
- link on the "link expired page"
- delete the account if expired, and let them register again

**Comment by ComputerGenius152** [comment]
I'm personally partial to the third method because of ease of implementation and getting rid of unverified accounts automatically.

**Comment by jdabtieu** [comment]
how is it easy to implement?

**Comment by ComputerGenius152** [comment]
One database query to check if the user is verified, and to delete the row if they're not :)
