### ISSUE TITLE
[FEATURE] Group problems by category in view

### ISSUE THREAD

**Issue by ComputerGenius152** [jdabtieu/CTFOJ#25]
## Is your feature request related to a problem? Please describe.
Group problems by category in view.

## Describe the solution you'd like
Group problems by category in view.

## Describe alternatives you've considered
Separate pages?

## Additional context
N/A

**Comment by jdabtieu** [comment]
should be easy enough
just change the SQL query in contests from
`SELECT * FROM table_name` to
`SELECT* FROM rable_name ORDER BY category ASC`
