### ISSUE TITLE
[BUG] Date & time not working

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#26]
Please use this template only for reporting bugs. Bug reports not using this template may be denied.

## Describe the bug
Entering date and time in the Create Contest menu shifts the timezone incorrectly

## Expected Behavior
Time should be converted to UTC on the client side, stored in UTC on the server, served to client in UTC, and converted to local on the client side

## Current Behavior
In one of the conversion steps the timezone is not being shifted correctly

## Possible Solution
??? have to look at code to see what part is responsible

## Steps to Reproduce
1. Create a contest, somewhere where your local time is not UTC

## Context (Environment)
Not relevant

## Additional Information
Please put anything not already mentioned here, including screenshots.

**Comment by BattleMage0231** [comment]
I can't seem to reproduce the problem on my local machine running Windows 10. I tested using UTC-9:00 (Alaska), UTC-5:00 (US & Canada), and UTC+14:00 (Kiritimati Island). The contest dates were all created, parsed, and displayed correctly as far as I can tell.

Could you give a more detailed description of how to reproduce the bug? Or maybe there is something I am not understanding correctly about UTC?

**Comment by ComputerGenius152** [comment]
Could not produce on local machine running Linux. Possible client-side misconfiguration between EST/EDT?

**Comment by jdabtieu** [comment]
yeah that was a fluke. No idea what happened. I couldn't reproduce either on Windows.

I think it's safe to say that being tested on 3 timezones, 3 separate machines running (likely) 3 different browsers on 2 different OS, this is probably an invalid bug.
