### ISSUE TITLE
Store problem descriptions, writeups, and hints in separate files instead of in database

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#27]
This gets rid of SQLite text's 65536 character limit
Also, better for editing and we can store the raw markdown

Writing problems in markdown --> Live preview using client-side markdown script
&nbsp;&nbsp;|
&nbsp;\\/
Store in markdown files
&nbsp;&nbsp;|
&nbsp;\\/
Serve to users
&nbsp;&nbsp;|
&nbsp;\\/
Rendered client side

This needs to get implemented ASAP
Related to #8 

Context: practice
- [x] Move stuff from db to filesystem
- [x] Link flask app to read from filesystem instead of from db
- [x] Link flask app to write to filesystem instead of db
- [ ] Render markdown client side

Context: contest
- [x] Move stuff from db to filesystem
- [x] Link flask app to read from filesystem instead of from db
- [x] Link flask app to write to filesystem instead of db
- [ ] Render markdown client side

Context: announcement
- [x] Move stuff from db to filesystem
- [x] Link flask app to read from filesystem instead of from db
- [x] Link flask app to write to filesystem instead of db
- [ ] Render markdown client side

Context: contest info
- [x] Move stuff from db to filesystem
- [x] Link flask app to read from filesystem instead of from db
- [x] Link flask app to write to filesystem instead of db
- [ ] Render markdown client side

**Comment by ComputerGenius152** [comment]
Possible import/export problem buttons?

**Comment by jdabtieu** [comment]
that's true, now that we will be storing markdown it will be quite easy to just serve the raw markdown

**Comment by jdabtieu** [comment]
Merged remaining to #8
