### ISSUE TITLE
[FEATURE] automated code quality checks

### ISSUE THREAD

**Issue by ComputerGenius152** [jdabtieu/CTFOJ#34]
## Is your feature request related to a problem? Please describe.
ensuring code quality and security to make it easier to maintain in the future.

## Describe the solution you'd like
pylint, codeql, and eventually codecov

## Describe alternatives you've considered
manual reviews, which shouldn't be the only component

## Additional context
i have github pro and can use the 3000 action minutes/month for this

**Comment by ComputerGenius152** [comment]
@jdabtieu thoughts?

**Comment by jdabtieu** [comment]
Yes, automated checks would be great

this + pytest would automate a lot of code review which would be nice
