### ISSUE TITLE
[FEATURE] CAPTCHA

### ISSUE THREAD

**Issue by ComputerGenius152** [jdabtieu/CTFOJ#35]
## Is your feature request related to a problem? Please describe.
We have many forms that would benefit from a CAPTCHA. This would stop contestants trying to brute-force problems as well.

## Describe the solution you'd like
Either reCAPTCHA or hCAPTCHA, preferably hCAPTCHA.

## Describe alternatives you've considered
Coinhive went out of business, and end-users might not like proof-of-work CAPTCHAs.

## Additional context
N/A

**Comment by jdabtieu** [comment]
yes, hcaptcha for loggin in/registering

also, if it's possible, a captcha should only be triggered if the user does too many requests at once

**Comment by ComputerGenius152** [comment]
Due to the prevalence of forms on our website, I'll just initially implement this for the register and login pages.
