### ISSUE TITLE
[BUG] Creating a new contest with the name of a contest + "info" results in persistent Error

### ISSUE THREAD

**Issue by BattleMage0231** [jdabtieu/CTFOJ#38]
Please use this template only for reporting bugs. Bug reports not using this template may be denied.

## Describe the bug
After creating a contest with id "abc", creating a contest with id "abcinfo" results in a persistent Internal Server Error whenever you go to the Contests tab.

## Expected Behavior
The contest should be created normally.

## Current Behavior
Because of the database architecture, a table is created for each contest with id named id + "info", and another one named id. If we manually create a table with id + "info", the application will be unable to create a table with id + "info", because it will already exist.

This also results in another error whenever the Contests page is opened because the application tries to access a file that doesn't exist.

## Possible Solution
- Check the id the user gives you for the suffix "info", and check if there is already a contest existing with the prefix
- Change the database architecture

## Steps to Reproduce
1. Create a contest named "abc".
2. Try to create a contest named "abcinfo".

## Context (Environment)
Irrelevant

## Additional Information
Related to #28 and #39

**Comment by jdabtieu** [comment]
Suspended, please refer to #28.
