### ISSUE TITLE
[BUG] Creating a new contest with prefix "sqlite_" results in persistent Error

### ISSUE THREAD

**Issue by BattleMage0231** [jdabtieu/CTFOJ#39]
Please use this template only for reporting bugs. Bug reports not using this template may be denied.

## Describe the bug
Creating a contest with an id with prefix "sqlite_" will result in a persistent Internal Server Exception whenever you go to the Contests tab.

## Expected Behavior
The contest should be created normally.

## Current Behavior
SQLite forbids table names starting with "sqlite_", as they are reserved for internal use. Creating a contest makes a table with a name of the contest id.

The error is persistent because the application tries to find a non-existing folder every time.

## Possible Solution
- Check for prefix "sqlite_" and sanitize it
- Change the database architecture

## Steps to Reproduce
1. Try to create a contest with name "sqlite_test"

## Context (Environment)
Irrelevant

## Additional Information
Related to #28 and #38

**Comment by jdabtieu** [comment]
Suspended, please refer to #28.
