### ISSUE TITLE
[FEATURE] Email notifications

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#4]

**Comment by ComputerGenius152** [comment]
Should be easy enough to do now that we have the helper functions to send emails.

**Comment by ComputerGenius152** [comment]
After further review, we currently have no formal mechanism to join contests; as such, notifying everyone in a contest (especially those who haven't submitted yet) would be impossible.

**Comment by ComputerGenius152** [comment]
Superseded by #44
