### ISSUE TITLE
[FEATURE] Central Admin Dashboard

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#5]
## Is your feature request related to a problem? Please describe.
Nope

## Describe the solution you'd like
Replacing Admin Tools dropdown with central dashboard
Include maintenance toggle in central dashboard

## Describe alternatives you've considered
Nope

## Additional context
Include the following instruction
```
To toggle maintenance mode: Make a request to /admin/maintenance while logged in as an admin

If you log out during maintenance mode, there is no way to turn it back off

The only thing maintenance mode should be used for is to make significant changes to the database that requires nobody writes to it during that time, as well as 5 minutes before a reboot to let users know that the site will be down momentarily. Once rebooted, maintenance mode will turn itself off
```

**Comment by ComputerGenius152** [comment]
Do you think a central page with button links + toggle for maintenance mode would be an improvement?

**Comment by jdabtieu** [comment]
yes
