### ISSUE TITLE
Better Tables

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#54]
Having each column as the same size looks ugly, so I'm going to try to make that better

**Comment by jdabtieu** [comment]
How does this look? 
![image](https://user-images.githubusercontent.com/62577178/102692011-9f887f00-41de-11eb-8e3e-8baeaf57a32b.png)

**Comment by ComputerGenius152** [comment]
looks good to me

**Comment by jdabtieu** [comment]
Fixed in 28e3a2a
