### ISSUE TITLE
[FEATURE] Implement points for practice

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#58]
## Is your feature request related to a problem? Please describe.
Contests already have points, practice should too. Although each question has point values it's meaningless

## Describe the solution you'd like
As a user, be able to see the number of points you've gotten from practice. Upon solving practice problems it should update a user's point count.

Edit: BTW, there should be no dynamic scoring for practice problems. Just static scoring. That should simplify things quite a bit.

**Comment by slightlyskepticalpotat** [comment]
Closed by https://github.com/jdabtieu/CTFOJ/pull/184
