### ISSUE TITLE
[FEATURE] Application Logs

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#6]
## Is your feature request related to a problem? Please describe.
Nope

## Describe the solution you'd like
Redirect stdout to file, redirect stderr to file, send email to admins for critical errors
Possibly use app.logger

## Describe alternatives you've considered
Nope

## Additional context
PythonAnywhere already has built-in logs, not sure about other hosts
This would be nice for self hosting though

**Comment by ComputerGenius152** [comment]
Closed by https://github.com/jdabtieu/CTFOJ/commit/306640811123348f3315266ee6e0a7d3bd0afa04

**Comment by jdabtieu** [comment]
is there a way in the settings.py to enable/disable logging?

the current settings would be great for prod but when writing code, I would want to see error codes/exceptions directly in the console

**Comment by ComputerGenius152** [comment]
Thanks for bringing this to my attention, I've made it log to both file and console now.
