### ISSUE TITLE
[FEATURE] Problem Statistics

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#60]
## Is your feature request related to a problem? Please describe.
It's annoying to manually sift through the submissions page to determine how many submissions are correct for a problem.

## Describe the solution you'd like
People should be able to view the percentage of correct submissions for each problem.

## Describe alternatives you've considered
An alternative is simply just the number of correct submissions.

## Additional context
Queries to do this:
```sql
Get # of correct submissions:
SELECT SUM(correct) FROM submissions WHERE problem_id='helloworld';

Get # of total submissions:
SELECT COUNT(correct) FROM submissions WHERE problem_id='helloworld';
```
and then just divide in Python

**Comment by slightlyskepticalpotat** [comment]
I'm thinking we could have it as a count next to each problem in the problems list, that links to the submissions page with the filter already applied.

**Comment by jdabtieu** [comment]
Yeah, in terms of statistics I'm thinking just the basics, like
- Number of subs
- Number of correct subs
- Percentage of subs correct
- Link to subs (with filter preapplied)
