### ISSUE TITLE
[FEATURE] Ability to edit flags

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#62]
## Is your feature request related to a problem? Please describe.
The only way to edit a problem's flag is by changing it using sqlite. This is annoying if you mistyped it or have to change it for some other reason.

## Describe the solution you'd like
An additional field in the edit problem page allowing the flag to be changed, in a manner similar to password reset (i.e. cannot see the previous flag, but you can set a new one if you'd like)

## Describe alternatives you've considered
The alternative is using executing `UPDATE problems SET flag='flag_goes_here' WHERE id='problem_id_goes_here';`

**Comment by ComputerGenius152** [comment]
I'll be working on this
