### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#63]
Lighthouse performance report is quite nasty, with a score of 35% for performance (locally hosted)

```
First Contentful Paint 3.8 s
Speed Index 3.9 s
Largest Contentful Paint 6.3 s
Time to Interactive 6.9 s
Total Blocking Time 1,300 ms
Cumulative Layout Shift 0.422
```

Opportunities
```
Enable text compression 2.7 s
Eliminate render-blocking resources 2.63 s
Remove unused JavaScript 1.35 s
Remove unused CSS 0.15 s
```

Additional Diagnostics
```
Image elements do not have explicit width and height
Serve static assets with an efficient cache policy 13 resources found
Minimize main-thread work 4.4 s
Reduce JavaScript execution time 1.6 s
```

We should also upgrade to Bootstrap 5.0.0 as it in longer relies on jQuery which means:
- It's faster
- Even if it did still rely on jQuery, 5.0.0 is faster than 4.5.3
- By rewriting a small amount of code, we can load jQuery at the bottom of the page, which means it's no longer render-blocking

**Comment by ComputerGenius152** [comment]
Hmm, what software are you using to host it locally?

The website's pretty lightweight, and the deployed site gets a 97 score.

![image](https://user-images.githubusercontent.com/31290848/106208102-d87a2300-6190-11eb-9595-46368517d5cc.png)

**Comment by jdabtieu** [comment]
I think I had some Chrome extensions getting in the way. I ran it against the deployed site and got 93%. Regardless, I think Lighthouse is computer-dependent, and a slower computer will get a worse score on the same site.

![image](https://user-images.githubusercontent.com/62577178/106220141-d91eb380-61a8-11eb-8cf7-45e35866f3f4.png)

All the resources (less favicon.png) are downloaded in 300ms, so clearly something is happening between 300ms and 2.4s on my computer.

According to Lighthouse, there is an estimated savings of 1.5s by eliminating render-blocking resources, and these are the 3 biggest offenders:
- Bootstrap CSS: 1400ms
- jQuery: 1120ms
- Bootstrap JS: 1280ms

**Comment by jdabtieu** [comment]
My estimate is that updating to Bootstrap 5.0.0 would reclaim 1 second from my 2.4s figure, and that removing jQuery would reclaim ~300ms.

Are you using Lighthouse simulating Desktop or Mobile?

**Comment by ComputerGenius152** [comment]
Desktop, mobile is at 65.

**Comment by jdabtieu** [comment]
Yeah, that's the thing.
Desktop performance is about as good as it gets, but mobile performance
isn't too great.

**Comment by jdabtieu** [comment]
On my local machine, I got these numbers
```
Lighthouse Benchmarks:
            Load  Interactive
88335d3     1.7s  4.5s (https://github.com/jdabtieu/CTFOJ/commit/88335d3e612acd3e57c67ed603c1887ae9627bfa)
master      5.0s  5.6s
```
