### ISSUE TITLE
[FEATURE] Allow users to resend confirmation email

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#80]
## Is your feature request related to a problem? Please describe.
If a user doesn't verify their account before the confirmation email expires, they are effectively locked out of that account and prevented from using their email to register a new account.

## Describe the solution you'd like
When trying to sign in with an unverified account, there should be an option to resend confirmation email.

## Describe alternatives you've considered
Asking users to re-register. This is probably actually better because they probably don't remember the password anymore. Regardless, the message will need be updated to make it more clear.

**Comment by slightlyskepticalpotat** [comment]
Currently if a user tries to sign in with an invalid verification link, it should delete their account and tell them to register again at (https://github.com/jdabtieu/CTFOJ/blob/master/src/application.py#L265). Is that not happening here?

**Comment by slightlyskepticalpotat** [comment]
![image](https://user-images.githubusercontent.com/31290848/108779221-8aa8ce80-7534-11eb-8b0f-1a37d4a3d935.png)
![image](https://user-images.githubusercontent.com/31290848/108779242-92687300-7534-11eb-8ed9-fc15d9fc1d28.png)

it works locally for me, I can just re-register

**Comment by jdabtieu** [comment]
Oh true, I forgot about that. The fact that one user didn't know what to do today shows that perhaps the message isn't clear enough. I think we could perhaps change it to
`Email verification link expired. Please register again <a href="/register">here</a>`
