### ISSUE TITLE
[BUG] No way to filter out submissions with contest "None"

### ISSUE THREAD

**Issue by slightlyskepticalpotat** [jdabtieu/CTFOJ#83]
Please use this template only for reporting bugs. Bug reports not using this template may be denied.

## Describe the bug
In the submissions list, non-contest problems are shown as having a contest id of "None". However, when you filter the contest id to "None", they don't show up.

## Expected Behavior
Submissions without a contest show up when filtering the contest id = None.

## Current Behavior
Nothing shows up

## Possible Solution
Prevent people from setting "None" as a contest id, and store non-contest problems with contest id of str("None").

## Steps to Reproduce
1. https://ctfmgci.pythonanywhere.com/admin/submissions?username=&problem_id=&contest_id=None&correct=

## Additional Information
Please put anything not already mentioned here, including screenshots.
![image](https://user-images.githubusercontent.com/31290848/109020087-a5d82300-7687-11eb-83b5-4309aa5e20bd.png)

**Comment by jdabtieu** [comment]
Fixed via b25fb4c and 308e6e0
