### ISSUE TITLE
[FEATURE] Code Cleanup

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#86]
Current code is quite messy in application.py and also in the HTML templates. Since there are no more high-priority issues (and only 3 other ones), it's probably about time to clean the code.

- [x] Python code compliance
    - Legacy code (from before v1.4.0) still isn't in compliance with PEP-8, with 60+ lines over 90 characters.
    - Even new code (from after v2.0.0) still isn't in compliance, with many lines over 90 characters
- [x] Simplifying & combining code
    - 4 paths contain complex code and as far as I'm aware, a lot of other paths have a lot of repetitive code that should be put in helpers.py
- [x] HTML templates frequently go over the 100-line limit for non-Python code, and they go unchecked because flake8 doesn't check it.
- [x] Some HTML templates don't belong in the right folder (e.g. contestnotify in admin folder and not contest folder)
- [x] JS code also frequently goes over 100 lines as well, but mostly inline code.
- [x] Installation script to speed up installation instead of having admins manually enter commands
- [x] A lot of code is poorly commented
- [x] Inconsistent JS code style
    - [x] Inconsistent variable naming (e.g. `box_shadow` vs `boxShadow` and indentation. Also, some semicolons may be missing)
    - [x] Remove evil inline JS!
- [x] ~~Some backend functions (that are called through JS only - e.g. `/admin/ban`) should really be an API endpoint rather than a generic endpoint~~

**Comment by slightlyskepticalpotat** [comment]
Just a note, the more people we can get on this the better.

**Comment by slightlyskepticalpotat** [comment]
Reminder to myself: check flake8 lint warnings and clear them

**Comment by slightlyskepticalpotat** [comment]
Also: we already have instructions in shell command form in install.md, so why not provide a .sh script? @jdabtieu

**Comment by jdabtieu** [comment]
> Also: we already have instructions in shell command form in install.md, so why not provide a .sh script? @jdabtieu

Yep, I was planning to do this for a while, but kept putting it off.

As you can see from [FBLA/install.py](https://github.com/jdabtieu/FBLA/blob/master/src/install.py) and [FBLA/INSTALL.md](https://github.com/jdabtieu/FBLA/blob/master/docs/INSTALL.md), creating an install script shortened the install steps by quite a lot
