### ISSUE TITLE
Automated tests using pytest

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#9]
Check that features work as intended, check for security and basic functionality

- Local File Inclusion
- SQL Injection, SSTI, XSS (non-admins)
- Session or JWT forgery

https://flask.palletsprojects.com/en/1.1.x/testing/

**Comment by ComputerGenius152** [comment]
@jdabtieu I'm working on this now, any specific tests you think are important

**Comment by jdabtieu** [comment]
Basic functionality (i.e. signing in, retrieving problems, contests)
Permissions (i.e. normal users shouldn't be allowed to access /admin/*)
Various other security checks (i.e. no SQL injection)
I'll add some of these as well, but here's where you can start

**Comment by ComputerGenius152** [comment]
@jdabtieu I've added a basic testing framework, feel free to add some tests. Later, I'll be adding some tests as well.
