### ISSUE TITLE
[FEATURE] Better Homepage

### ISSUE THREAD

**Issue by slightlyskepticalpotat** [jdabtieu/CTFOJ#92]
## Is your feature request related to a problem? Please describe.
When we look at other popular online judges like DMOJ and CodeForces, they have a more interactive home page with information about the site instead of a login page. We should consider doing that.

## Describe the solution you'd like
A home page instead of directing everyone to login, maybe with some stats of users registered, submission counts, and the like. Additionally, I'm not sure announcements should require login.

## Describe alternatives you've considered
The current login page works, but it isn't very pretty. 

## Additional context
![image](https://user-images.githubusercontent.com/31290848/114294031-3a94b580-9a69-11eb-87c6-1e47f5c7d8a0.png)
![image](https://user-images.githubusercontent.com/31290848/114294035-408a9680-9a69-11eb-882e-75d7f8e46b7e.png)

**Comment by jdabtieu** [comment]
Added an experimental homepage option, if you set `USE_HOMEPAGE` to true, you can create a homepage in the template folder called `unauth_index.html`.

Currently only way to use and set this is to change the filesystem and reload the app, so I'm probably going to add another way to edit the homepage without console access.

**Comment by jdabtieu** [comment]
Editing homepage implemented. Now I just need to figure out sanitization and then this issue can be closed.
