### ISSUE TITLE
[FEATURE] Better emails

### ISSUE THREAD

**Issue by jdabtieu** [jdabtieu/CTFOJ#94]
## Is your feature request related to a problem? Please describe.
Current emails are very bland. Accounts-related email (e.g. register, password reset) are very bland. When notifying participants of a contest, styling is not enabled either.

## Describe the solution you'd like
Emails should look better & more professional. Additionally, some sort of basic styling should be enabled for announcement emails

**Comment by slightlyskepticalpotat** [comment]
Breakdown of what needs to be done for myself:

- [ ] Rewrite emails to sound more professional
- [ ] Convert to HTML emails with website theme
- [ ] Test all of the emails work, ideally in CI too
